"""Shared helpers for the paper's table generators (standard library only).

Every generator writes one `tabular` body (rows only, no \\begin{tabular}) to
paper/tex/generated/<name>.tex, prints what it wrote, and ends with `STATUS: PASS`
or `STATUS: FAIL <reason>` (exit 1). Lean-derived generators read the PINNED
commit through `git show` so that the paper lane's pin (DECISIONS.md Q-F) is
respected; pass --commit at freeze to re-sync.
"""
import os
import re
import subprocess
import sys

ROOT = os.environ.get("R44_ROOT") or os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
DEFAULT_COMMIT = "d90313a717"
DEFAULT_OUT = os.path.join(ROOT, "paper", "tex", "generated")


def git_show(commit, path):
    """Bytes of `path` at `commit` (read-only)."""
    return subprocess.run(
        ["git", "-C", ROOT, "show", f"{commit}:{path}"], check=True, capture_output=True
    ).stdout.decode("utf-8")


_ESC = {
    "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
    "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
}


_UNI = {
    "χ": r"$\chi$", "π": r"$\pi$", "α": r"$\alpha$", "β": r"$\beta$", "ρ": r"$\rho$", "η": r"$\eta$",
    "σ": r"$\sigma$", "δ": r"$\delta$", "ε": r"$\varepsilon$", "Ω": r"$\Omega$", "φ": r"$\varphi$",
    "Φ": r"$\Phi$", "ψ": r"$\psi$", "λ": r"$\lambda$", "μ": r"$\mu$", "θ": r"$\theta$", "Λ": r"$\Lambda$",
    "≠": r"$\ne$", "≤": r"$\le$", "≥": r"$\ge$", "→": r"$\to$", "⇒": r"$\Rightarrow$", "⇔": r"$\Leftrightarrow$",
    "∈": r"$\in$", "∉": r"$\notin$", "⊆": r"$\subseteq$", "⊂": r"$\subset$", "∪": r"$\cup$", "∩": r"$\cap$",
    "∀": r"$\forall$", "∃": r"$\exists$", "∧": r"$\wedge$", "∨": r"$\vee$", "¬": r"$\neg$",
    "×": r"$\times$", "·": r"$\cdot$", "−": "-", "–": "--", "—": "---", "…": r"\dots", "′": r"$'$",
    "‖": r"$\|$", "⟨": r"$\langle$", "⟩": r"$\rangle$", "∞": r"$\infty$", "√": r"$\surd$",
    "ℝ": r"$\mathbb{R}$", "ℤ": r"$\mathbb{Z}$", "ℕ": r"$\mathbb{N}$", "ℚ": r"$\mathbb{Q}$",
    "²": r"$^2$", "³": r"$^3$", "ⁿ": r"$^n$", "⁻": r"$^-$", "¹": r"$^1$", "₀": r"$_0$", "₁": r"$_1$", "₂": r"$_2$",
    "§": r"\S{}", "°": r"$^\circ$", "±": r"$\pm$", "“": "``", "”": "''", "‘": "`", "’": "'", " ": "~",
}


def tex(s):
    """Escape plain text for LaTeX; `code` spans become \\texttt{...}; common Unicode math
    symbols are translated; any other non-ASCII character aborts the generator (extend _UNI)."""
    out = []
    parts = re.split(r"(`[^`]*`)", s)
    for p in parts:
        if p.startswith("`") and p.endswith("`") and len(p) >= 2:
            inner = "".join(_UNI.get(ch, _ESC.get(ch, ch)) for ch in p[1:-1])
            out.append(r"\texttt{" + inner + "}")
        else:
            out.append("".join(_UNI.get(ch, _ESC.get(ch, ch)) for ch in p).replace("/", "/\\allowbreak{}"))
    res = "".join(out)
    bad = sorted({ch for ch in res if ord(ch) > 127})
    if bad:
        finish(False, "unmapped non-ASCII characters " + ", ".join(f"U+{ord(c):04X} {c}" for c in bad))
    return res


def leanname(n):
    """A Lean declaration name, typeset breakable at underscores (macros.tex defines \\lean)."""
    return r"\lean{" + tex(n) + "}"


def pathtt(p):
    """A file path in typewriter, breakable after every slash and underscore."""
    return r"\texttt{" + tex(p).replace("/", "/\\allowbreak{}").replace(r"\_", r"\_\allowbreak{}") + "}"


def num(n):
    """Thousands-grouped integer for LaTeX math mode: 6862 -> 6{,}862."""
    s = f"{int(n):,}"
    return s.replace(",", "{,}")


def write_rows(out_dir, name, rows, header_comment, colspec="ll", header=None, longtable=None):
    """Write a complete booktabs `tabular` (the section file \\input{}s it outside any
    tabular, which is robust; \\input inside a tabular is not). With `longtable={'caption':..,
    'label':..}` a page-breaking `longtable` with the caption on top and the header repeated is
    written instead (for the tall tables), to be \\input outside any float."""
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, name + ".tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"% generated by paper/scripts/{name}.py; {header_comment}\n")
        if longtable:
            f.write("{\\small\n\\begin{longtable}{" + colspec + "}\n")
            f.write("\\caption{" + longtable["caption"] + "}\\label{" + longtable["label"] + "}\\\\\n")
            f.write("\\toprule\n" + (" & ".join(header) + " \\\\\n\\midrule\n" if header else "") + "\\endfirsthead\n")
            f.write("\\toprule\n" + (" & ".join(header) + " \\\\\n\\midrule\n" if header else "") + "\\endhead\n")
            f.write("\\bottomrule\n\\endfoot\n")
            for r in rows:
                f.write(" & ".join(r) + " \\\\\n")
            f.write("\\end{longtable}}\n")
        else:
            f.write("\\begin{tabular}{" + colspec + "}\n\\toprule\n")
            if header:
                f.write(" & ".join(header) + " \\\\\n\\midrule\n")
            for r in rows:
                f.write(" & ".join(r) + " \\\\\n")
            f.write("\\bottomrule\n\\end{tabular}\n")
    print(f"wrote {os.path.relpath(path, ROOT)} ({len(rows)} rows{', longtable' if longtable else ''})")
    return path


def finish(ok, reason=""):
    if ok:
        print("STATUS: PASS")
        sys.exit(0)
    print(f"STATUS: FAIL {reason}")
    sys.exit(1)


def common_args(parser, lean=True):
    parser.add_argument("--out", default=DEFAULT_OUT, help="output directory (paper/tex/generated)")
    if lean:
        parser.add_argument("--commit", default=DEFAULT_COMMIT,
                            help="commit whose Lean files are read (the paper's pin; re-run at freeze)")
    return parser
