#!/usr/bin/env bash
# WRITING_PLAN.md step 18: build the arXiv source package of the paper from paper/tex.
# Produces paper/tex/arxiv/r44-paper-<tag>.tar.gz containing main.tex, macros.tex, the section,
# appendix and figure files, generated/*.tex, the two PDF illustrations of figures/print-preview/
# and the two vector hierarchy illustrations, main.bbl (arXiv needs the bbl,
# not the bib) and a README. Run from the repository root after a clean latexmk build.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TEX="$ROOT/paper/tex"
TAG="${1:-paper-v2}"
OUT="$TEX/arxiv"
[[ "$TAG" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "Invalid package label" >&2; exit 1; }
mkdir -p "$OUT"
PACKAGE="$OUT/r44-$TAG.tar.gz"
if [[ -e "$PACKAGE" ]]; then
  echo "Package already exists; choose a new label to preserve it: $PACKAGE" >&2
  exit 1
fi
STAGE="$(mktemp -d "$OUT/stage-$TAG.XXXXXX")"
mkdir -p "$STAGE/generated" "$STAGE/figures/print-preview"
cd "$TEX"
latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex > build.out 2>&1
python3 check_log.py main.log
cp main.tex macros.tex sec*.tex app*.tex notation.tex fig_*.tex main.bbl "$STAGE/"
# publication_doi.tex is intentionally excluded: the Zenodo DOI is printed only
# in the repository PDF, not in the arXiv source version.
cp generated/*.tex "$STAGE/generated/"
cp "$ROOT"/figures/r44_parent_cluster.pdf "$ROOT"/figures/r44_patch64.pdf "$STAGE/figures/"
cp "$ROOT"/figures/print-preview/figure1-corrected.pdf "$ROOT"/figures/print-preview/figure3-corrected.pdf "$STAGE/figures/print-preview/"
# arXiv builds from the package root: point the graphics path and the bibliography there
sed -i 's|\\graphicspath{{../../figures/}}|\\graphicspath{{figures/}}|' "$STAGE/macros.tex"
sed -i 's|\\bibliography{../refs}|\\bibliography{refs}|' "$STAGE/main.tex"
cp "$ROOT/paper/refs.bib" "$STAGE/refs.bib"
cat > "$STAGE/00README.txt" <<EOF
A strongly aperiodic monotile in three dimensions — arXiv source package ($TAG).
This is a locally prepared package; its label does not assert publication of a GitHub or Zenodo release.
Build: pdflatex main; bibtex main; pdflatex main; pdflatex main (main.bbl is included).
Class amsart; packages: amsmath amssymb amsthm mathtools graphicx booktabs longtable array xcolor
enumitem caption microtype hyperref cleveref tikz (positioning, arrows.meta).
generated/*.tex are tables and figures produced by the repository's scripts (paper/scripts/)
from the certificates and the pinned Lean development; figures/*.pdf are the carrier illustrations generated by
paper/scripts/hierarchy_figures.py from the exact child poses; figures/print-preview/*.pdf are the illustrations drawn by
figures/print-preview/build_preview.py from solid/r44_solid.json with the exaggerations stated in
their captions (feature bases x5, signed heights x80). Repository: https://github.com/ioannist/six-birds-tiles (mathematical baseline commit d90313a717).
EOF
# verify the package builds on its own
( cd "$STAGE" && latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex > build.out 2>&1 && python3 "$TEX/check_log.py" main.log )
( cd "$STAGE" && latexmk -c main.tex > /dev/null 2>&1 )
python3 - "$STAGE" <<'PY'
from pathlib import Path
import sys
stage = Path(sys.argv[1])
for name in ("build.out", "main.pdf"):
    (stage / name).unlink(missing_ok=True)
PY
tar -C "$STAGE" -czf "$PACKAGE" .
echo "package: $PACKAGE"
sha256sum "$PACKAGE"
