#!/usr/bin/env bash
# WRITING_PLAN.md step 18: build the arXiv source package of the paper from paper/tex.
# Produces paper/tex/arxiv/r44-paper-<tag>.tar.gz containing main.tex, macros.tex, the section,
# appendix and figure files, generated/*.tex, the two PDF illustrations of figures/print-preview/
# and the two vector hierarchy illustrations, main.bbl (arXiv needs the bbl,
# not the bib) and a README. Run from the repository root after a clean latexmk build.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TEX="$ROOT/paper/tex"
TAG="${1:-paper-v1}"
OUT="$TEX/arxiv"
STAGE="$OUT/stage"
rm -rf "$STAGE"; mkdir -p "$STAGE/generated" "$STAGE/figures/print-preview"
cd "$TEX"
latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex > build.out 2>&1
python3 check_log.py main.log
cp main.tex macros.tex sec*.tex app*.tex notation.tex fig_*.tex main.bbl "$STAGE/"
# publication_doi.tex is intentionally excluded: the Zenodo DOI is printed only
# in the repository PDF, not in the arXiv source version.
cp generated/*.tex "$STAGE/generated/"
cp "$ROOT"/figures/r44_parent_cluster.pdf "$ROOT"/figures/r44_patch64.pdf "$STAGE/figures/"
cp "$ROOT"/figures/print-preview/figure1-corrected.pdf "$ROOT"/figures/print-preview/figure3-corrected.pdf "$STAGE/figures/print-preview/"
# arXiv builds from the package root: point the graphics path and the bibliography there
sed -i 's|\\graphicspath{{../../figures/}}|\\graphicspath{{figures/}}|' "$STAGE/macros.tex"
sed -i 's|\\bibliography{../refs}|\\bibliography{refs}|' "$STAGE/main.tex"
cp "$ROOT/paper/refs.bib" "$STAGE/refs.bib"
cat > "$STAGE/00README.txt" <<EOF
A strongly aperiodic monotile in three dimensions — arXiv source package (intended release tag $TAG; creation pending).
Build: pdflatex main; bibtex main; pdflatex main; pdflatex main (main.bbl is included).
Class amsart; packages: amsmath amssymb amsthm mathtools graphicx booktabs longtable array xcolor
enumitem caption microtype hyperref cleveref tikz (positioning, arrows.meta).
generated/*.tex are tables and figures produced by the repository's scripts (paper/scripts/)
from the certificates and the pinned Lean development; figures/*.pdf are the carrier illustrations generated by
paper/scripts/hierarchy_figures.py from the exact child poses; figures/print-preview/*.pdf are the illustrations drawn by
figures/print-preview/build_preview.py from solid/r44_solid.json with the exaggerations stated in
their captions (feature bases x5, signed heights x80). Repository: https://github.com/ioannist/six-birds-tiles (intended release tag $TAG; creation pending; mathematical baseline commit dd2735d9bd).
EOF
# verify the package builds on its own
( cd "$STAGE" && latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex > build.out 2>&1 && python3 "$TEX/check_log.py" main.log )
( cd "$STAGE" && latexmk -c main.tex > /dev/null 2>&1; rm -f build.out main.pdf )
tar -C "$OUT" -czf "$OUT/r44-$TAG.tar.gz" stage
echo "package: $OUT/r44-$TAG.tar.gz"
sha256sum "$OUT/r44-$TAG.tar.gz"
