#!/usr/bin/env python3
"""Fig. 3.3 as a table (FIGURES.md): the 44-contact atlas from
certificates/candidate_certificate.json, as (frame, offset) pairs: the frame is a permutation p
and sign vector s acting by G(x)_i = s_i x_{p_i}, the offset the integer translation of the
neighbouring chair relative to a root in the identity pose. Two side-by-side tabulars."""
import argparse
import json
import os

from _texutil import ROOT, common_args, finish

def fmt_frame(fr):
    p, s = fr
    return "$(" + ",".join(str(x) for x in p) + ")$ $(" + ",".join("+" if x > 0 else "-" for x in s) + ")$"


def main():
    ap = common_args(argparse.ArgumentParser(description=__doc__), lean=False)
    args = ap.parse_args()
    c = json.load(open(os.path.join(ROOT, "certificates", "candidate_certificate.json"), encoding="utf-8"))
    atlas = c["legal_contacts"]
    frames = {json.dumps(a[0]) for a in atlas}
    rows = []
    for k, (fr, off) in enumerate(atlas):
        rows.append((k + 1, fmt_frame(fr), "$(" + ",".join(str(x) for x in off) + ")$"))
    half = (len(rows) + 1) // 2
    os.makedirs(args.out, exist_ok=True)
    path = os.path.join(args.out, "atlas_44_table.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write("% generated by paper/scripts/atlas_44.py from certificates/candidate_certificate.json (legal_contacts)\n")
        for part in (rows[:half], rows[half:]):
            f.write("\\begin{tabular}{rll}\n\\toprule\n\\# & frame $(p)\\,(s)$ & offset \\\\\n\\midrule\n")
            for k, fr, off in part:
                f.write(f"{k} & {fr} & {off} \\\\\n")
            f.write("\\bottomrule\n\\end{tabular}\\hfill\n")
    print(f"wrote {os.path.relpath(path, ROOT)} ({len(rows)} contacts, {len(frames)} distinct frames)")
    finish(len(rows) == 44 and len(frames) == 19, "atlas size or frame count differs from 44 / 19")


if __name__ == "__main__":
    main()
