#!/usr/bin/env python3
"""Fig. 2.2 (FIGURES.md): the 24 exposed panels of the chair, numbered as in the paper, with
the sign pattern of their features, drawn from solid/native_panels.csv as six axis views
(one per outward normal direction): each unit panel is a square carrying its number and its
eight signed magnitudes at the mark positions (+-1/8, +-1/4) and (+-1/4, +-1/8)."""
import argparse
import csv
import os
from fractions import Fraction

from _texutil import ROOT, common_args, finish

MARKS = [(-1, -2), (-1, 2), (1, -2), (1, 2), (-2, -1), (-2, 1), (2, -1), (2, 1)]  # in eighths


def main():
    ap = common_args(argparse.ArgumentParser(description=__doc__), lean=False)
    args = ap.parse_args()
    rows = list(csv.DictReader(open(os.path.join(ROOT, "solid", "native_panels.csv"), encoding="utf-8")))
    os.makedirs(args.out, exist_ok=True)
    out = os.path.join(args.out, "fig_carrier_panels.tex")
    S = 1.7  # cm per unit
    views = [(0, -1), (0, 1), (1, -1), (1, 1), (2, -1), (2, 1)]
    names = {0: "x", 1: "y", 2: "z"}
    with open(out, "w", encoding="utf-8") as f:
        f.write("% generated by paper/scripts/carrier_panels.py from solid/native_panels.csv\n")
        f.write("\\begin{tikzpicture}[x=1cm,y=1cm,font=\\scriptsize]\n")
        for vi, (axis, sign) in enumerate(views):
            ox, oy = (vi % 3) * (2 * S + 0.9), -(vi // 3) * (2 * S + 1.1)
            t1, t2 = [k for k in range(3) if k != axis]
            f.write(f"  \\node[anchor=south west,font=\\small] at ({ox},{oy + 2*S + 0.05}) {{normal ${'+' if sign > 0 else '-'}{names[axis]}$; axes ${names[t1]},{names[t2]}$}};\n")
            f.write(f"  \\draw[gray!50] ({ox},{oy}) grid[step={S}] ({ox + 2*S},{oy + 2*S});\n")
            for r in rows:
                if int(r["normal_axis"]) != axis or int(r["outward_sign"]) != sign:
                    continue
                c = [Fraction(r["center_x"]), Fraction(r["center_y"]), Fraction(r["center_z"])]
                u, v = float(c[t1]), float(c[t2])
                x0, y0 = ox + (u - 0.5) * S, oy + (v - 0.5) * S
                f.write(f"  \\draw[thick] ({x0},{y0}) rectangle ({x0 + S},{y0 + S});\n")
                f.write(f"  \\node[font=\\footnotesize\\bfseries] at ({x0 + 0.5*S},{y0 + 0.5*S}) {{{r['panel']}}};\n")
                for k, (mu, mv) in enumerate(MARKS):
                    a = int(r[f"a_{k}"])
                    mx, my = x0 + (0.5 + mu / 8) * S, y0 + (0.5 + mv / 8) * S
                    f.write(f"  \\node[font=\\tiny,text={'red!70!black' if a > 0 else 'blue!70!black'}] at ({mx},{my}) {{${'+' if a > 0 else '-'}{abs(a)}$}};\n")
        f.write("\\end{tikzpicture}\n")
    print(f"wrote {os.path.relpath(out, ROOT)} ({len(rows)} panels)")
    finish(len(rows) == 24, "panel count differs from 24")


if __name__ == "__main__":
    main()
