#!/usr/bin/env python3
"""Fig. 8.1 (FIGURES.md): the modular coincidence as a TikZ picture, drawn from the JSON output
of verify/substitution_modular_coincidence.py: the sizes of the possible-label sets by depth
(histogram) and the path of residues to the coincidence address a = (0,0,2) at depth 3, where
the set collapses to the single label i = 78."""
import argparse
import json
import os
import subprocess
import sys

from _texutil import ROOT, common_args, finish


def main():
    ap = common_args(argparse.ArgumentParser(description=__doc__), lean=False)
    args = ap.parse_args()
    proc = subprocess.run([sys.executable, os.path.join(ROOT, "verify", "substitution_modular_coincidence.py")],
                          check=True, capture_output=True, text=True)
    sub = json.loads(proc.stdout.strip().splitlines()[-1])
    hist = {d: dict((int(sz), int(cnt)) for sz, cnt in pairs) for d, pairs in sub["coincidence_label_set_sizes"]}
    path = sub["coincidence_path"]
    a = sub["coincidence_address_a"]
    i = sub["coincidence_label_i"]
    labels = sub["labels"]
    os.makedirs(args.out, exist_ok=True)
    out = os.path.join(args.out, "fig_coincidence.tex")
    with open(out, "w", encoding="utf-8") as f:
        f.write("% generated by paper/scripts/coincidence_tree.py from verify/substitution_modular_coincidence.py\n")
        f.write("\\begin{tikzpicture}[x=1cm,y=1cm,font=\\small,\n"
                "  lvl/.style={draw,rounded corners=1pt,inner sep=3pt,align=center,minimum width=2.6cm},\n"
                "  arr/.style={-{Latex[length=1.6mm]},thick}]\n")
        # left: the path
        f.write(f"  \\node[lvl] (d0) at (0,0) {{root: all ${labels}$ labels}};\n")
        prev = "d0"
        for depth, r in enumerate(path, start=1):
            sizes = hist[depth]
            # the path's own set size is the smallest size present at this depth on the path; the
            # certificate records only the histogram, so we display the histogram at each depth
            hist_txt = "all-address histogram: " + ", ".join(f"{cnt}\\,addresses with {sz}" for sz, cnt in sorted(sizes.items()))
            f.write(f"  \\node[lvl] (d{depth}) at (0,{-1.5*depth}) {{residue $({','.join(str(x) for x in r)})$ at depth {depth}\\\\ \\scriptsize {hist_txt}}};\n")
            f.write(f"  \\draw[arr] ({prev}) -- (d{depth});\n")
            prev = f"d{depth}"
        f.write(f"  \\node[lvl,thick,fill=black!6] (fin) at (0,{-1.5*(len(path)+1)}) {{address $a=({','.join(str(x) for x in a)})$ mod $2^{{{len(path)}}}$: one label, $i={i}$}};\n")
        f.write(f"  \\draw[arr] ({prev}) -- (fin);\n")
        f.write("\\end{tikzpicture}\n")
    print(f"wrote {os.path.relpath(out, ROOT)}; histogram {hist}")
    finish(hist.get(3, {}).get(1) == 336 and i == 78 and a == [0, 0, 2], "coincidence data differ from the certified values")


if __name__ == "__main__":
    main()
