#!/usr/bin/env python3
"""Fig. 6.1 as a table (FIGURES.md): the 33 first shells of certificates/candidate_certificate.json
(each an exact cover of the 22 shell cells by legal neighbours, given as indices into the atlas
table), the candidate parent each proposes (role_options: the child index of the root), and the
central-completion verdict (passed / dead) for the 32 outer-root shells."""
import argparse
import json
import os

from _texutil import ROOT, common_args, finish


def main():
    ap = common_args(argparse.ArgumentParser(description=__doc__), lean=False)
    args = ap.parse_args()
    c = json.load(open(os.path.join(ROOT, "certificates", "candidate_certificate.json"), encoding="utf-8"))
    sols, opts = c["solutions"], c["role_options"]
    passed = set(int(x) for x in c["central_passed"])   # shell indices (outer-root shells with a completion)
    dead = set(int(x) for x in c["central_dead"])       # shell indices without one
    rows = []
    for k, (s, o) in enumerate(zip(sols, opts)):
        verdict = "central" if k not in passed and k not in dead else ("completable" if k in passed else "impossible")
        rows.append((k + 1, ",".join(str(x + 1) for x in s), ",".join(str(x) for x in o), verdict))
    n_central = sum(1 for r in rows if r[3] == "central")
    n_pass = sum(1 for r in rows if r[3] == "completable")
    n_dead = sum(1 for r in rows if r[3] == "impossible")
    os.makedirs(args.out, exist_ok=True)
    path = os.path.join(args.out, "first_shells_table.tex")
    half = (len(rows) + 1) // 2
    with open(path, "w", encoding="utf-8") as f:
        f.write("% generated by paper/scripts/first_shells.py from certificates/candidate_certificate.json\n")
        for part_index, part in enumerate((rows[:half], rows[half:])):
            f.write("\\begin{tabular}{rlll}\n\\toprule\nshell & atlas contacts & parent & completion \\\\\n\\midrule\n")
            for k, cells, o, v in part:
                f.write(f"{k} & {cells} & {o} & {v} \\\\\n")
            f.write("\\bottomrule\n\\end{tabular}\n")
            if part_index == 0:
                # The two tables are each nearly a text line wide, so placing
                # them in one paragraph makes TeX wrap the second at the left
                # margin.  End the paragraph explicitly: the surrounding
                # figure's \centering then centers both rows independently.
                f.write("\\par\\smallskip\n")
    print(f"wrote {os.path.relpath(path, ROOT)} ({len(rows)} shells; central {n_central}, completable {n_pass}, impossible {n_dead})")
    ok = len(rows) == 33 and all(len(o) == 1 for o in opts) and n_central == 1 and n_pass == 14 and n_dead == 18
    finish(ok, "shell counts differ from 33 / 1 / 14 / 18 or a shell proposes more than one parent")


if __name__ == "__main__":
    main()
