#!/usr/bin/env python3
"""Appendix C: the `Hypotheses` record verbatim from lean/R44/R44/LogicalSpine.lean at the pinned
commit (field declarations; docstrings omitted), as a verbatim block. Re-run with --commit at freeze."""
import argparse
import os
import re

from _texutil import ROOT, common_args, finish, git_show


def main():
    ap = common_args(argparse.ArgumentParser(description=__doc__))
    args = ap.parse_args()
    src = git_show(args.commit, "lean/R44/R44/LogicalSpine.lean")
    m = re.search(r"^structure Hypotheses : Prop where\n((?:  .*\n|\n(?=  ))*)", src, re.M)
    body = m.group(1)  # empty at a pin where the record has no fields
    # drop docstrings (/-- ... -/), keep the declaration lines exactly
    body = re.sub(r"\s*/--.*?-/", "", body, flags=re.S)
    lines = ["structure Hypotheses : Prop where"] + [l for l in body.split("\n") if l.strip()]
    fields = [l for l in lines[1:] if re.match(r"^  [a-z_0-9]+ :", l) or re.match(r"^  [a-z_0-9]+ :$", l)]
    # verbatim cannot wrap: split lines longer than 66 characters after an implication arrow,
    # continuing with a deeper indentation (whitespace only; the tokens are unchanged)
    wrapped = []
    for l in lines:
        indent = len(l) - len(l.lstrip())
        parts = l.split(" → ")
        cur = parts[0]
        for part in parts[1:]:
            if len(cur) + 3 + len(part) > 66:
                wrapped.append(cur + " →")
                cur = " " * (indent + 4) + part
            else:
                cur = cur + " → " + part
        wrapped.append(cur)
    lines = wrapped
    os.makedirs(args.out, exist_ok=True)
    path = os.path.join(args.out, "hypotheses_record.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"% generated by paper/scripts/hypotheses_record.py from lean/R44/R44/LogicalSpine.lean at {args.commit}; docstrings omitted\n")
        f.write("\\begin{verbatim}\n" + "\n".join(lines) + "\n\\end{verbatim}\n")
    nonascii = sorted({ch for ch in "\n".join(lines) if ord(ch) > 127})
    print(f"wrote {os.path.relpath(path, ROOT)} ({len(fields)} fields; non-ASCII: {' '.join(f'U+{ord(c):04X}' for c in nonascii) or 'none'})")
    finish(len(fields) == 0, f"expected an empty record at the pin, found {len(fields)} fields")


if __name__ == "__main__":
    main()
