#!/usr/bin/env python3
"""Fig. 6.2 (FIGURES.md): hierarchy nesting drawn from the actual child poses of
certificates/candidate_certificate.json: the 64-chair patch obtained by refining the native chair
twice, shown in the slice 0 <= z < 1 (unit cells as squares in the xy-plane), coloured by
level-1 supertile, with the level-1 supertile outlines (the eight copies of 2P) and the level-2
outline (4P) drawn on top. Cells are computed exactly by applying the signed-permutation poses to
the seven unit cubes of the chair."""
import argparse
import json
import os

from _texutil import ROOT, common_args, finish


def act(frame, t, cell):
    """Image of the unit cube with min corner `cell` under pose (frame, t): min corner of the image."""
    p, s = frame
    lo = [0, 0, 0]
    for i in range(3):
        a = cell[p[i]]
        lo[i] = s[i] * a + t[i] if s[i] > 0 else s[i] * (a + 1) + t[i]
    return tuple(lo)


def compose(G, t, H, u):
    """(G,t) o (H,u): frame GH and translation t + G u."""
    p, s = G
    q, r = H
    perm = [q[p[i]] for i in range(3)]
    sign = [s[i] * r[p[i]] for i in range(3)]
    Gu = [s[i] * u[p[i]] for i in range(3)]
    return (perm, sign), [t[i] + Gu[i] for i in range(3)]


def main():
    ap = common_args(argparse.ArgumentParser(description=__doc__), lean=False)
    args = ap.parse_args()
    c = json.load(open(os.path.join(ROOT, "certificates", "candidate_certificate.json"), encoding="utf-8"))
    children = [(tuple(ch[0][0]), tuple(ch[0][1]), list(ch[1])) for ch in c["children"]]
    chair = [(a, b, cc) for a in (0, 1) for b in (0, 1) for cc in (0, 1) if (a, b, cc) != (1, 1, 1)]
    # refine the identity pose twice: level-2 supertile = 4P, made of 8 level-1 supertiles (2P), of 8 chairs each
    def refine(poses):
        out = []
        for G, t, parent in poses:
            for k, (q, r, u) in enumerate(children):
                H, tt = compose(G, t, (list(q), list(r)), u)
                out.append((H, [2 * t[i] + (tt[i] - t[i]) for i in range(3)], parent if parent is not None else k))
        return out
    # a chair in pose (G,t) refines to eight chairs in poses (G H_k, 2t + G u_k) (PROOFS_registered R§1)
    def refine_exact(poses):
        out = []
        for G, t, parent in poses:
            for k, (q, r, u) in enumerate(children):
                (perm, sign), Gu = compose(G, [0, 0, 0], (list(q), list(r)), u)
                out.append(((perm, sign), [2 * t[i] + Gu[i] for i in range(3)], parent if parent is not None else k))
        return out
    level1 = refine_exact([(([0, 1, 2], [1, 1, 1]), [0, 0, 0], None)])   # 8 chairs = one 2P
    level2 = refine_exact(level1)                                          # 64 chairs = one 4P; parent index = level-1 supertile
    cells = {}
    for G, t, parent in level2:
        for cell in chair:
            cells[act(G, t, cell)] = parent
    # two refinements of the chair (side 2) give 4P (side 8): the 8x8x8 block minus the corner block [4,8)^3
    expected = {(x, y, z) for x in range(8) for y in range(8) for z in range(8) if not (x >= 4 and y >= 4 and z >= 4)}
    ok = len(cells) == 64 * 7 and set(cells) == expected
    os.makedirs(args.out, exist_ok=True)
    out = os.path.join(args.out, "fig_nesting_slice.tex")
    colors = ["red!30", "blue!30", "green!40", "orange!40", "violet!30", "cyan!40", "brown!40", "gray!40"]
    S = 0.75
    with open(out, "w", encoding="utf-8") as f:
        f.write("% generated by paper/scripts/nesting_slice.py from certificates/candidate_certificate.json (children)\n")
        f.write("\\begin{tikzpicture}[x=1cm,y=1cm,font=\\scriptsize]\n")
        for (x, y, z), parent in sorted(cells.items()):
            if z != 0:
                continue
            f.write(f"  \\fill[{colors[parent]}] ({x*S},{y*S}) rectangle ({(x+1)*S},{(y+1)*S});\n")
            f.write(f"  \\draw[gray!60,thin] ({x*S},{y*S}) rectangle ({(x+1)*S},{(y+1)*S});\n")
        # level-1 outlines: boundary edges between cells of different parents (or the outside), in the slice
        slice_cells = {(x, y): parent for (x, y, z), parent in cells.items() if z == 0}
        for (x, y), parent in slice_cells.items():
            for dx, dy, seg in ((1, 0, ((x+1, y), (x+1, y+1))), (-1, 0, ((x, y), (x, y+1))), (0, 1, ((x, y+1), (x+1, y+1))), (0, -1, ((x, y), (x+1, y)))):
                nb = slice_cells.get((x + dx, y + dy))
                if nb != parent:
                    (ax, ay), (bx, by) = seg
                    f.write(f"  \\draw[very thick] ({ax*S},{ay*S}) -- ({bx*S},{by*S});\n")
        f.write(f"  \\draw[line width=1.6pt,black] (0,0) rectangle ({8*S},{8*S});\n")
        f.write(f"  \\node[anchor=north,font=\\small,align=center] at ({4*S},-0.15) {{slice $0\\le z<1$ of the $64$-chair patch $4\\carrier$ (side $8$):\\\\ cells coloured by level-1 supertile; thick lines: level-1 outlines, level-2 outline}};\n")
        f.write("\\end{tikzpicture}\n")
    print(f"wrote {os.path.relpath(out, ROOT)} ({len(cells)} cells, {sum(1 for k in cells if k[2]==0)} in the slice)")
    finish(ok, "the 64 chairs do not partition the 4x4x4 block exactly")


if __name__ == "__main__":
    main()
