#!/usr/bin/env python3
"""Embed the canonical R44 data into viewer/r44_data.js so viewer/index.html runs from file://.

Reads only solid/r44_solid.json (exact rational mesh + feature patches), the child poses in
solid/r44_solid.json, and certificates/candidate_certificate.json (44-contact atlas).
Everything is converted to floats for display; the rational files stay authoritative.

    python3 viewer/build_data.py
"""
from __future__ import annotations

import hashlib
import json
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def frac(v):
    return [float(Fraction(c)) for c in v]


def main():
    solid_path = ROOT / "solid" / "r44_solid.json"
    cert_path = ROOT / "certificates" / "candidate_certificate.json"
    solid = json.loads(solid_path.read_text())
    cert = json.loads(cert_path.read_text())

    verts = [frac(v) for v in solid["vertices"]]
    lookup = {tuple(round(c, 9) for c in v): i for i, v in enumerate(verts)}
    features = []
    for p in solid["patches"]:
        apex = frac(p["apex"])
        base = [frac(q) for q in p["base"]]
        centre = [sum(q[i] for q in base) / 4 for i in range(3)]
        axis = max(range(3), key=lambda i: abs(apex[i] - centre[i]))
        sign = 1 if p["coefficient"] > 0 else -1
        # outward normal: apex offset direction for a bump, opposite for a dent
        n = [0.0, 0.0, 0.0]
        n[axis] = (1.0 if apex[axis] > centre[axis] else -1.0) * sign
        features.append({
            "role": p["role"],
            "panel": p["face"],
            "coef": p["coefficient"],
            "apex": lookup[tuple(round(c, 9) for c in apex)],
            "base": [lookup[tuple(round(c, 9) for c in q)] for q in base],
            "centre": centre,
            "normal": n,
        })
    assert len(features) == 192
    children = solid["substitution_children"]
    atlas = cert["legal_contacts"]
    data = {
        "name": solid["name"],
        "source_sha256": {
            "solid/r44_solid.json": hashlib.sha256(solid_path.read_bytes()).hexdigest(),
            "certificates/candidate_certificate.json": hashlib.sha256(cert_path.read_bytes()).hexdigest(),
        },
        "eta": float(Fraction(solid["base_halfwidth"])),
        "height_unit": float(Fraction(solid["height_unit"])),
        "vertices": verts,
        "triangles": solid["triangles"],
        "features": features,
        "children": children,
        "atlas": atlas,
        "chair_cells": solid["base_unit_cubes"],
    }
    out = ROOT / "viewer" / "r44_data.js"
    out.write_text("// GENERATED by viewer/build_data.py from the canonical files; do not edit.\n"
                   "window.R44_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")
    print(f"wrote {out} ({out.stat().st_size // 1024} KB): {len(verts)} vertices, "
          f"{len(solid['triangles'])} triangles, {len(features)} features, {len(atlas)} contacts")


if __name__ == "__main__":
    main()
